# Generated by Django 4.2 on 2025-05-21 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'profile__role': 'student'}, related_name='classrooms', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(blank=True, limit_choices_to={'profile__role': 'teacher'}, related_name='teaching_classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
